#!/usr/bin/env python3
"""Generate selected Ladybug arcade characters in CoCo 3 assembly format.

The authoritative character shapes are the 512 8x8, 2bpp pixel grids in
assets/arcade/chars.json.  Each --char specification selects one character,
names its assembly label, and optionally maps arcade pens 0..3 to GIME palette
indices 0..15:

    --char INDEX:LABEL[:P0,P1,P2,P3]

The arcade character sheet follows the rotated cabinet display.  Pass
--rotate ccw when target glyphs must appear upright on the unrotated CoCo 3
framebuffer.

The output is deterministic and intentionally contains only selected tiles so
the 16 KB cartridge is not consumed by the complete arcade character ROM.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Iterable, Sequence


EXPECTED_CHAR_COUNT = 512
CHAR_WIDTH = 8
CHAR_HEIGHT = 8

# Current 16-entry GIME RGB palette contract verified in Phase 2.4.
GIME_PALETTE = (
    0x00, 0x30, 0x08, 0x3F,
    0x20, 0x10, 0x18, 0x28,
    0x38, 0x04, 0x02, 0x01,
    0x06, 0x03, 0x05, 0x07,
)

LABEL_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_char_spec(value: str) -> tuple[int, str, tuple[int, int, int, int]]:
    parts = value.split(":")
    if len(parts) not in (2, 3):
        raise argparse.ArgumentTypeError(
            "character must be INDEX:LABEL or INDEX:LABEL:P0,P1,P2,P3"
        )

    try:
        index = int(parts[0], 0)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid character index: {parts[0]}") from exc

    label = parts[1]
    if not LABEL_RE.fullmatch(label):
        raise argparse.ArgumentTypeError(f"invalid assembly label: {label}")

    pen_map = (0, 1, 2, 3)
    if len(parts) == 3:
        try:
            mapped = tuple(int(item, 0) for item in parts[2].split(","))
        except ValueError as exc:
            raise argparse.ArgumentTypeError("pen map entries must be integers") from exc
        if len(mapped) != 4 or any(item < 0 or item > 15 for item in mapped):
            raise argparse.ArgumentTypeError(
                "pen map must contain four palette indices in the range 0..15"
            )
        pen_map = mapped

    return index, label, pen_map


def load_chars(path: Path) -> list[list[list[int]]]:
    try:
        chars = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read character data from {path}: {exc}") from exc

    if not isinstance(chars, list) or len(chars) != EXPECTED_CHAR_COUNT:
        raise ValueError(f"expected {EXPECTED_CHAR_COUNT} characters in {path}")

    for char_index, char in enumerate(chars):
        if not isinstance(char, list) or len(char) != CHAR_HEIGHT:
            raise ValueError(f"character {char_index} must contain {CHAR_HEIGHT} rows")
        for row_index, row in enumerate(char):
            if not isinstance(row, list) or len(row) != CHAR_WIDTH:
                raise ValueError(
                    f"character {char_index} row {row_index} must contain {CHAR_WIDTH} pixels"
                )
            if any(type(pixel) is not int or pixel < 0 or pixel > 3 for pixel in row):
                raise ValueError(
                    f"character {char_index} row {row_index} contains a non-2bpp pixel"
                )

    return chars


def pack_row(row: Sequence[int], pen_map: Sequence[int]) -> list[int]:
    mapped = [pen_map[pixel] for pixel in row]
    return [(mapped[i] << 4) | mapped[i + 1] for i in range(0, CHAR_WIDTH, 2)]


def rotate_char_ccw(char: Sequence[Sequence[int]]) -> list[list[int]]:
    """Rotate one square character 90 degrees counter-clockwise."""
    return [
        [char[x][CHAR_WIDTH - 1 - y] for x in range(CHAR_HEIGHT)]
        for y in range(CHAR_WIDTH)
    ]


def format_fcb(values: Iterable[int]) -> str:
    return "        fcb     " + ",".join(f"${value:02X}" for value in values)


def render_include(
    source: Path,
    chars: Sequence[Sequence[Sequence[int]]],
    specs: Sequence[tuple[int, str, tuple[int, int, int, int]]],
    rotation: str = "none",
) -> str:
    if rotation not in ("none", "ccw"):
        raise ValueError(f"unsupported character rotation: {rotation}")

    labels: set[str] = set()
    source_label = "/".join(source.parts[-3:])
    lines = [
        "; Generated by scripts/build_gfx.py. Do not edit.",
        f"; Source: {source_label}",
        "",
        "; 16-entry GIME RGB palette used by generated character data.",
        "palette_table",
        format_fcb(GIME_PALETTE[:8]),
        format_fcb(GIME_PALETTE[8:]),
    ]

    for index, label, pen_map in specs:
        if index < 0 or index >= len(chars):
            raise ValueError(f"character index {index} is outside 0..{len(chars) - 1}")
        if label in labels or label == "palette_table":
            raise ValueError(f"duplicate generated label: {label}")
        labels.add(label)
        char = chars[index]
        if rotation == "ccw":
            char = rotate_char_ccw(char)

        lines.extend(
            [
                "",
                f"; Arcade character {index}; rotation {rotation}; pen map "
                + ",".join(map(str, pen_map))
                + ".",
                label,
            ]
        )
        for row in char:
            packed = pack_row(row, pen_map)
            lines.append(format_fcb(packed) + "     ; " + " ".join(map(str, row)))

    return "\n".join(lines) + "\n"


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write(content)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chars", type=Path, required=True, help="authoritative chars.json")
    parser.add_argument("--output", type=Path, required=True, help="generated assembly include")
    parser.add_argument(
        "--rotate",
        choices=("none", "ccw"),
        default="none",
        help="rotate selected characters before packing; default: none",
    )
    parser.add_argument(
        "--char",
        dest="char_specs",
        action="append",
        type=parse_char_spec,
        required=True,
        help="INDEX:LABEL[:P0,P1,P2,P3]; repeat to emit more characters",
    )
    args = parser.parse_args()

    chars = load_chars(args.chars)
    content = render_include(args.chars, chars, args.char_specs, args.rotate)
    write_if_changed(args.output, content)
    print(f"gfx: generated {len(args.char_specs)} character(s) -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
