from pathlib import Path
import json,hashlib,collections,subprocess
root=Path('E:/projects/ladybug');w=Path('C:/Users/19029/.codex/worktrees/bug-046-word-carryover/ladybug');r=root/'repro'
trace=r/'bug058-rebind-profile-20260927.json';d=json.loads(trace.read_text());phases={}
for count in (3,4):
 rows=[s for s in d['samples'] if s['requested_count']==count][-16:]
 assert len(rows)==16 and all(s['active']==count and s['death']==0 and 5 not in s['audio_before']['slots']+s['audio_after']['slots'] for s in rows)
 phases[str(count)]={'worklists':16,'vbord_interval_counts':dict(collections.Counter(str(b['vbord']-a['vbord']) for a,b in zip(rows,rows[1:]))),'vbord_parity_counts':dict(collections.Counter(str(s['vbord']&1) for s in rows)),'clock_meaning':'VBlank counter at each dispatch; intervals are between consecutive sampled dispatches, not movement-call or distance measurements.'}
main=(w/'src/main.s').read_text();enemy=(w/'src/enemy_runtime.s').read_text()
assert '        lda     FB_SIM_SEQ+1\n        anda    #$01\n        bne     main_render' in main
assert 'et_find_movement\n        lda     LAST_FRAME\n        anda    #1\n        bne     et_render_test' in enemy
e={'ticket':'BUG-058','fit_commit':'cba5205','rom_sha256':d['rom_sha256'],'natural_report':'Player slows with four enemies; enemies appear normal; three or fewer enemies play acceptably.','source_facts':{'player':'main_game_tick_normal consumes PLAYER_TICK_PENDING; main_alive arms it after an even FB_SIM_SEQ completed epoch, unless PICKUP_TIMER holds it.','enemy':'enemy_tick_impl et_find_movement admits movement when LAST_FRAME hardware VBlank parity is even, subject to normal death/freeze/direction conditions.','publication':'framebuffer_irq_impl increments FRAMES at every VBlank and FB_SIM_SEQ only when a pending completed image publishes.','step':'Ordinary player and enemy motion both advance one packed byte horizontally or 320 framebuffer bytes vertically: two pixels.'},'retained_phase_observations':phases,'interpretation':'Confirmed source clock inconsistency plus observed even-parity aliasing supports the reported relative slowdown. With two VBlanks per committed image, player cadence can halve while even-phase enemy movement remains admitted every dispatch. Not a direct moving-player displacement measurement. Opposite hardware parity could suppress enemy movement instead.','reassessment':'Leading explanation now includes movement scheduling as well as renderer cost. High-risk remains; no production change approved. Existing frozen-epoch policy and 27000 target remain. Synchronizing enemy parity alone would not restore player wall-clock pace or meet the frame target.','next_discriminating_probe':'Reuse existing monitor harness on identified cold artifact; count actual player_tick and enemy movement entries, completed epochs, hardware VBlanks and actor displacement over short three/four-enemy straight-motion windows without pickup/gate/death/freeze interruptions. Each phase <=45 seconds; success requires named calls plus valid motion and byte/mapping identity; absent or interrupted window fails. Include opposite VBlank parity if designing a scheduling fix.','trace_sha256':hashlib.sha256(trace.read_bytes()).hexdigest(),'source_hashes':{name:hashlib.sha256((w/name).read_bytes()).hexdigest() for name in ('src/main.s','src/enemy_runtime.s')},'code_changes':False,'manual_game_left_running':True}
(r/'bug058-player-cadence-observation-20260927.json').write_text(json.dumps(e,indent=2)+'\n')
sections={
'wiki/internal/tickets/bug-058-three-enemy-slowdown.html':'<section id="player-relative-slowdown-20260927"><h2>Natural four-enemy player slowdown and clock discrepancy — 2026-09-27</h2><p>User reports on fitted cba5205 / ROM f67c3424…a5b981: player slows once four enemies are present, while enemies appear to retain normal pace; three or fewer play acceptably. This confirms remaining natural performance failure, not overall acceptance. The game remains running; no source edits or forced state applied to that session.</p><p>Read-only source diagnosis finds different movement clocks. main_game_tick_normal consumes PLAYER_TICK_PENDING; main_alive arms it from even FB_SIM_SEQ completed-epoch parity. Enemy et_find_movement instead tests LAST_FRAME hardware-VBlank parity. IRQ increments FRAMES on every VBlank but FB_SIM_SEQ only when a completed image publishes. Both ordinary movement steps are two pixels. This contradicts the documented shared committed-epoch staggering rule.</p><p>Retained current-ROM post-release trace: sixteen three-enemy worklists have consecutive VBlank intervals one (12), two (2), three (1), with eight even and eight odd dispatch counters. Sixteen four-enemy worklists have fifteen consecutive two-VBlank intervals and all sixteen counters even. Thus the enemy parity gate is repeatedly admitted while player scheduling remains every other completed epoch. This supports the relative-speed report. Actual moving-player call counts/displacements are not retained, so quantitative actor speeds are not claimed. An opposite parity alignment could suppress enemy movement instead.</p><p>Project-management reassessment: leading explanation expands from renderer overload to movement scheduling; High-risk remains. Lower-cost source and retained-trace review discriminates against assuming all actors must slow uniformly. Next bounded test: actual player/enemy movement calls, displacement, committed epochs and hardware VBlanks in short uninterrupted three/four-enemy windows, with built/live byte and mapping identity. Existing harness, 45-second phases, interrupted or missing motion fails. Opposite VBlank parity matters for any future scheduling design. No clock fix is approved: synchronizing enemies alone would slow them to the player cadence and would not recover player wall-clock pace or meet 27,000. <a href="../../../repro/bug058-player-cadence-observation-20260927.json">Source facts, trace counts and next probe</a>. BUG-058 remains Proposed.</p></section>',
'wiki/internal/implementation/ping-pong-framebuffer.html':'<section id="enemy-clock-discrepancy-20260927"><h2>Current enemy parity differs from the committed-epoch rule</h2><p>Read-only review of cba5205 identifies a discrepancy: player pending movement follows FB_SIM_SEQ, but enemy_runtime.s et_find_movement tests LAST_FRAME. Under the retained four-enemy workload, each image takes two VBlanks and dispatch stays on even hardware parity. The enemy gate can then admit every dispatch while player movement remains every second completed epoch. This is separate from the renderer exceeding its cycle budget; aligning enemy parity alone cannot restore full wall-clock player speed. Existing frozen-epoch policy remains authoritative. <a href="../tickets/bug-058-three-enemy-slowdown.html#player-relative-slowdown-20260927">Observed facts, limits and unapproved next scheduling investigation</a>.</p></section>',
'wiki/internal/sources/index.html':'<section id="bug058-movement-clock-sources-20260927"><h2>2026-09-27 — Movement clock review</h2><p>Reviewed cba5205 src/main.s main_game_tick_normal/main_alive/player_tick and src/enemy_runtime.s et_find_movement/framebuffer_irq_impl. Confirmed source mismatch between player completed-epoch parity and enemy hardware-VBlank parity; compared against ping-pong publication policy and retained current-ROM three/four-enemy dispatch counters. No source changes or direct moving-player speed measurement. <a href="../tickets/bug-058-three-enemy-slowdown.html#player-relative-slowdown-20260927">Natural report and discriminating evidence</a>.</p></section>',
'wiki/internal/log.html':'<section id="bug058-player-relative-log-20260927"><h2>2026-09-27 — BUG-058 player-relative natural slowdown</h2><p>Recorded user report: four enemies slow player while enemies appear normal; three or fewer acceptable. PM/debugger source and retained-counter review identifies player FB_SIM_SEQ versus enemy LAST_FRAME parity discrepancy, with all sixteen four-enemy dispatches on even hardware parity and two-VBlank intervals. Reassessed High-risk scope before further runtime experiments; direct movement-rate proof remains pending. No implementation, clock workaround or timing waiver. Game left running. Ingested scheduler findings and updated framebuffer policy discrepancy and canonical ticket; retained concise source/hash/trace evidence.</p></section>'}
for path,section in sections.items():
 p=root/path;s=p.read_text(encoding='utf-8');ident=section.split('id="',1)[1].split('"',1)[0];assert ident not in s;p.write_text(s.replace('</main>',section+'\n</main>',1),encoding='utf-8')
 base=subprocess.check_output(['git','show','HEAD:'+path],cwd=root).decode('utf-8');staged=base.replace('</main>',section+'\n</main>',1).encode('utf-8');blob=subprocess.check_output(['git','hash-object','-w','--stdin'],input=staged,cwd=root).decode().strip();subprocess.run(['git','update-index','--cacheinfo','100644',blob,path],cwd=root,check=True)
print(json.dumps(phases));print('Source clock discrepancy and natural observation recorded; no runtime probe or production change.')
